#!/bin/bash

set -e

. /usr/share/debconf/confmodule

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi


# Idempotent configurations
if [ "$ACTION" != 'triggered' ]; then
    # Set env vars
    db_get ks-base/sysname
    sysname="$RET"
    db_get ks-base/primary-user
    u="$RET"
    db_get ks-base/primary-user-home
    home="$RET"
    RP="$home/Runtime"
    db_get ks-base/mountpoint
    MOUNTPOINT="$RET"

    # Prepare config directories
    mkdir -p "$home/.config/syncthing"


    # Link Configs
    srcconf="$RP/Configs/syncthing/$sysname.config.xml"
    targconf="$home/.config/syncthing/config.xml"
    if [ ! -e "$srcconf" ]; then
        >&2 echo "W: Required config file '$srcconf' doesn't exist! You should fix this or things might night work correctly."
        >&2 echo "   Installing without machine-specific config...."
    else
        ln -snf "$srcconf" "$targconf" || true
    fi


    # Add custom systemd config
    sysdconfdir="/etc/systemd/system/syncthing@$u.service.d"
    mkdir -p "$sysdconfdir"

    if [ "$MOUNTPOINT" != "/" ]; then
        sysdmount="$(echo "$MOUNTPOINT" | sed -r 's#(^/|/$)##g' | sed 's#/#-#g').mount"
        {
            echo "[Unit]"
            echo "Requires=$sysdmount"
            echo "After=$sysdmount"
        } > "$sysdconfdir/ksmountpoint.conf"
    fi
    systemctl daemon-reload || true


    # Enable and start syncthing service for user
    unit="syncthing@$u.service"
    if ! systemctl is-enabled "$unit" >/dev/null; then
        systemctl enable "$unit" || true
    fi

    # Regardless of which machine, try to start the service
    if ! systemctl is-active "syncthing@$u.service" >/dev/null; then
        if [ -e "$home/.config/syncthing/config.xml" ]; then
            systemctl start "syncthing@$u.service" || true
        else
            >&2 echo "E: Config file for syncthing not found. Not starting service."
        fi
    fi

    # Start syncthing config watcher (first run only)
    if dpkg --compare-versions "$2" lt "1.0.4"; then
        systemctl enable --now syncthing-config-watcher.timer || true
    fi


    # Increase file watch limit
    CURLIM="$(cat /proc/sys/fs/inotify/max_user_watches)"
    if [ -n "$CURLIM" ] && [ "$CURLIM" -lt "204800" ]; then
        echo "fs.inotify.max_user_watches=204800" | sudo tee /etc/sysctl.d/90-ks-syncthing.conf >/dev/null || true
        echo 204800 > /proc/sys/fs/inotify/max_user_watches
    fi
fi




# Triggers
#if [ "$ACTION" == 'triggered' ]; then
#fi

