#!/bin/bash

set -e

. /usr/share/debconf/confmodule

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi



function ln_reqd_config() {
    if [ ! -e "$1" ]; then
        >&2 echo "W: Required config file '$1' doesn't exist! You should fix this or things might night work correctly."
    fi
    ln -snf "$1" "$2"
}




# Idempotent actions
if [ "$ACTION" != 'triggered' ]; then
    # Set env vars
    nm=hub1
    db_get ks-configs/runtime-path
    RP="$RET"

    # Sanity check and installation preps
    if [ -n "$SUDO_USER" ]; then
        HOME="/home/$SUDO_USER"
    fi
    if [ -z "$HOME" ]; then
        >&2 echo "E: Your \$HOME variable isn't set, but this is necessary to install certain"
        >&2 echo "   configurations. You should install this using 'sudo' from your normal user"
        >&2 echo "   account, rather than using 'su' or the root account."
        exit 2
    fi


    # Prepare config directories
    mkdir -p "$HOME/.config/syncthing"


    # Link Configs
    ln_reqd_config "$RP/Configs/ddnsd/$nm.config" /etc/ddnsd/config
    ln_reqd_config "$RP/Configs/hd-idle/$nm.config" /etc/default/hd-idle
    ln_reqd_config "$RP/Configs/syncthing/$nm.config.xml" "$HOME/.config/syncthing/config.xml"
fi







# Run if triggered
#if [ "$ACTION" == 'triggered' ]; then
#fi

