#!/bin/bash

set -e

. /usr/share/debconf/confmodule

if [ -z "$HOME" ]; then
    if [ -n "$SUDO_USER" ]; then
        HOME="/home/$SUDO_USER"
    elif [ -n "$USER" ]; then
        HOME="/home/$USER"
    else
        >&2 "E: Can't find \$HOME environment variable! Don't know what to do."
        exit 1
    fi
fi

db_input high ks-mountpoint/mountpoint || true
db_go

db_get ks-mountpoint/mountpoint
MOUNTPOINT="$(echo "$RET" | sed "s#~#$HOME#")"
if [ "$MOUNTPOINT" != "$RET" ]; then
    db_set ks-mountpoint/mountpoint "$MOUNTPOINT"
fi
