#!/bin/bash

set -e

#. /usr/share/debconf/confmodule

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi

# Idempotent configurations
#if [ "$ACTION" != 'triggered' ]; then
#fi




# Triggers
#if [ "$ACTION" == 'triggered' ]; then
#fi

