#!/bin/bash

set -e

. /usr/share/debconf/confmodule

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi


# Idempotent configurations
if [ "$ACTION" != 'triggered' ]; then
    # Set env vars
    db_get ks-base/mountpoint
    MOUNTPOINT="$RET"

    # Add custom systemd config
    svcname="insync-portable@$SUDO_USER.service"
    sysdconfdir="/etc/systemd/system/$svcname.d"
    mkdir -p "$sysdconfdir"

    if [ ! -e "$sysdconfdir/ksmountpoint.conf" ]; then
        sysdmount="$(echo "$MOUNTPOINT" | sed -r 's#(^/|/$)##g' | sed 's#/#-#g').mount"
        {
            echo "[Unit]"
            echo "Requires=$sysdmount"
            echo "After=$sysdmount"
        } > "$sysdconfdir/ksmountpoint.conf"
        systemctl daemon-reload || true


        # Restart only if already started
        if systemctl is-active "$svcname" >/dev/null; then
            systemctl restart "$svcname" || true
        else
            >&2 echo "W: $svcname not active, so not starting"
        fi
    fi
fi




# Triggers
#if [ "$ACTION" == 'triggered' ]; then
#fi

