#!/bin/bash

set -e

. /usr/share/debconf/confmodule

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi



db_get ks-configs/runtime-path
RUNTIME_PATH="$RET"

if [ ! -d "$RUNTIME_PATH" ]; then
    {
        echo "Couldn't find runtime path \`$RUNTIME_PATH\`. Are you sure you've copied it over"
        echo "to this instance yet?"
        echo
        echo "You'll have to ensure this directory is in place before proceeding with the install."
    } >&2
    exit 2
fi

echo "Runtime configs found."


