#!/bin/bash

set -e

. /usr/share/debconf/confmodule

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi



if [ "$ACTION" != "triggered" ]; then
    db_get ks-base/primary-user-home
    RUNTIME_PATH="$RET/Runtime"

    if [ ! -d "$RUNTIME_PATH/Configs" ] || [ ! -d "$RUNTIME_PATH/Data" ]; then
        {
            echo "E: Couldn't find runtime path \`$RUNTIME_PATH/Configs\` or"
            echo "   \`$RUNTIME_PATH/Data\`. Are you sure you're set up correctly"
            echo "   on this machine?"
            echo
            echo "   You'll have to ensure these directories are in place before proceeding with the install."
        } >&2
        exit 2
    fi
fi


