#!/bin/bash

set -e

. /usr/share/debconf/confmodule

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi


# Idempotent configurations
if [ "$ACTION" != 'triggered' ]; then
    # Set env vars
    db_get ks-base/sysname
    sysname="$RET"
    db_get ks-base/primary-user-home
    home="$RET"
    RP="$home/Runtime"
    db_get ks-base/mountpoint
    MOUNTPOINT="$RET"


    # Link Configs
    srcconf="$RP/Configs/ddnsd/$sysname.config"
    targconf=/etc/ddnsd/config
    if [ ! -e "$srcconf" ]; then
        >&2 echo "W: Required config file '$srcconf' doesn't exist! You should fix this or things might night work correctly."
        >&2 echo "   Installing anyway...."
    fi
    ln -snf "$srcconf" "$targconf" || true


    # Add custom systemd config
    sysdconfdir="/etc/systemd/system/ddnsd.service.d"
    mkdir -p "$sysdconfdir"

    sysdmount="$(echo "$MOUNTPOINT" | sed -r 's#(^/|/$)##g' | sed 's#/#-#g').mount"
    {
        echo "[Unit]"
        echo "Requires=$sysdmount"
        echo "After=$sysdmount"
    } > "$sysdconfdir/ksmountpoint.conf"
    systemctl daemon-reload || true


    # Enable and start ddnsd service (only on fresh install)
    if [ -z "$2" ]; then
        systemctl enable --now ddnsd.service || true
    fi
fi




# Triggers
#if [ "$ACTION" == 'triggered' ]; then
#fi

