#!/bin/bash

set -e

. /usr/share/debconf/confmodule

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi

function ln_reqd_config() {
    if [ ! -e "$1" ]; then
        >&2 echo "W: Required config file '$1' doesn't exist! You should fix this or things might night work correctly."
    fi
    ln -snf "$1" "$2"
}



# Idempotent
if [ "$ACTION" != 'triggered' ]; then
    # Set env vars
    nm=home
    db_get ks-configs/runtime-path
    RP="$RET"


    # Sanity check and installation preps
    if [ -n "$SUDO_USER" ]; then
        HOME="/home/$SUDO_USER"
    fi
    if [ -z "$HOME" ]; then
        >&2 echo "E: Your \$HOME variable isn't set, but this is necessary to install certain"
        >&2 echo "   configurations. You should install this using 'sudo' from your normal user"
        >&2 echo "   account, rather than using 'su'."
        exit 2
    fi
    mkdir -p "$HOME/.config/syncthing"


    # Link Configs
    ln_reqd_config "$RP/Configs/syncthing/$nm.config.xml" "$HOME/.config/syncthing/config.xml"

    user="$SUDO_USER"
    if [ -z "$user" ]; then
        user="$USER"
    fi
    systemctl enable --now "syncthing@$user.timer"
fi

