#!/bin/bash

. /usr/share/debconf/confmodule

if [ "$1" != 'upgrade' ]; then
    user="$SUDO_USER"
    if [ -z "$user" ]; then
        user="$USER"
    fi
    systemctl disable --now "syncthing@$user.timer"
    rm "$HOME/.config/syncthing/config.xml"
fi

